XBotCore:
  config_path: "external/qppvm/config/cogimon_impedance.yaml"

XBotInterface:
  urdf_path: "external/qppvm/config/cogimon_floating_base/cogimon.urdf"
  srdf_path: "external/qppvm/config/cogimon_gazebo.srdf"
  joint_map_path: "configs/ADVR_shared/cogimon/joint_map/cogimon_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
  plugins: ["HomingExample", "InvDynPlugin"] #"QPPVMPlugin"] #, "XBotRTCommunication"] 
  io_plugins: ["CartesianIO"]
  
NRTPlugins:
  plugins: [] #"HomingExample"]
  
TransmissionPlugins:
  plugins: [] #["CogimonImpedanceAnkles"] #CogimonImpedanceAnkles CogimonAnkles
  

SimulationOptions:
  verbose_mode: "true"

CartesianInterface:
  solver: "OpenSot"
  problem_description:
    stack:
      - ["Waist", "LFoot", "RFoot", "CoM"]
    constraints: []

    Waist:
      type: "Cartesian"
      distal_link: "Waist"
      base_link: "world"

    LFoot:
      type: "Cartesian"
      distal_link: "l_sole"
      base_link: "world"

    RFoot:
      type: "Cartesian"
      distal_link: "r_sole"
      base_link: "world"

    CoM:
      type: "Com"

